[build]
  command = "yarn build"
  publish = "build"
  ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF -- . ':!data/' ':!README.md'"

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  GENERATE_SOURCEMAP = "false"